database:
  dbms: postgresql  # Main database for application (str).
  driver: asyncpg  # Async or sync db driver (str).
  host: localhost  # Database host (str). Example (localhost or database (if using docker compose))
  port: 5432  # Database port (int)
  user: postgres  # Database user (str)
  password: postgres # Database password (str, optional)
  database: handbook_service # Database name (str)
  debug: false  # Print database log output (bool)


authentication:
  enabled: false # Enable authentication (bool)
  api_key: super-secret-api-key # Secret key (str)
