database:
  dbms:  # Main database for application (str)
  driver:  # Async or sync db driver (str)
  host:  # Database host (str)
  port:  # Database port (int)
  user:  # Database user (str)
  password:  # Database password (str, optional)
  database:  # Database name (str)
  pool_size:  # The size of the pool to be maintained (int)
  max_overflow:  # The maximum overflow size of the pool (int)
  debug:  # Print database log output (bool)
