services:
  db:
    image: postgres:17-alpine
    container_name: database
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./test_data.sql:/docker-entrypoint-initdb.d/test_data.sql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=handbook_service
    ports:
      - "5432:5432"
    networks:
      - handbook-service

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: handbook-service
    restart: always
    depends_on:
      - db
    volumes:
      - "./config.yaml:/handbook-service/config.yaml"
    ports:
      - "8000:8000"
    networks:
      - handbook-service

volumes:
  pgdata:

networks:
  handbook-service:
