"""init tables

Revision ID: a33b318f1bba
Revises:
Create Date: 2025-05-21 11:27:16.005123

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'a33b318f1bba'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'activity',
        sa.Column('activity_id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=50), nullable=False),
        sa.Column('parent_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['parent_id'], ['activity.activity_id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('activity_id'),
    )
    op.create_table(
        'building',
        sa.Column('building_id', sa.Integer(), nullable=False),
        sa.Column('address', sa.String(length=255), nullable=False),
        sa.Column('latitude', sa.NUMERIC(precision=9, scale=6), nullable=False),
        sa.Column('longitude', sa.NUMERIC(precision=10, scale=6), nullable=False),
        sa.PrimaryKeyConstraint('building_id'),
    )
    op.create_table(
        'organization',
        sa.Column('organization_id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('building_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['building_id'], ['building.building_id']),
        sa.PrimaryKeyConstraint('organization_id'),
    )
    op.create_table(
        'organization_activity',
        sa.Column('organization_id', sa.Integer(), nullable=False),
        sa.Column('activity_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['activity_id'], ['activity.activity_id']),
        sa.ForeignKeyConstraint(['organization_id'], ['organization.organization_id']),
        sa.PrimaryKeyConstraint('organization_id', 'activity_id'),
    )
    op.create_table(
        'organization_phone',
        sa.Column('phone_id', sa.Integer(), nullable=False),
        sa.Column('number', sa.String(length=20), nullable=False),
        sa.Column('organization_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['organization_id'], ['organization.organization_id']),
        sa.PrimaryKeyConstraint('phone_id'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('organization_phone')
    op.drop_table('organization_activity')
    op.drop_table('organization')
    op.drop_table('building')
    op.drop_table('activity')
    # ### end Alembic commands ###
